key_help
txt={ ...
    'To toggle menus and see related keys';...
    '    ,      Unhide left menu';...
    '    .      Unhide right menu';...
    'Keys not listed in menus:';...
    '    :      Command'; ...
    '    1-9    Number menu'
    '    h      Prev stimulus'; ...
    '    l      Next/New stimulus'; ...
    '    k      Increment Value';...
    '    j      Decrement Value';...
    '    Space  Toggle crosshairs';...
    '    Tab    Toggle mask';...
    '    Esc    clear keys';...
    '    z      change crosshair shape';...
    '    x      toggle nonius cross between dichoptic and binocular';...
    '    dx     remove stimulus';...
    '    dd     cut stimulus';...
    '    y      copy stimulus';...
    '    p      paste stimulus (after cutting stimulus';...
    '    ';...
    'Press ''q'' to close this help window';...
    'Press ''c'' for a list of commands';...
    'Press ''n'' for key commands in number menu';...
};
